Blog app - integration specs for views and fix n+1 problems
fibini/Rails-Blog pull request #9
Opened 2022-09-27 22:40 UTC by fibini

Make sure that the N+1 problem is solved when fetching all posts and their comments for a user. 
Integration specs
- Use Capybara to write integration tests for each view in your project.

User index page:

- I can see the username of all other users.
- I can see the profile picture for each user.
- I can see the number of posts each user has written.
- When I click on a user, I am redirected to that user's show page.

User show page:
- I can see the user's profile picture.
- I can see the user's username.
- I can see the number of posts the user has written.
- I can see the user's bio.
- I can see the user's first 3 posts.
- I can see a button that lets me view all of a user's posts.
- When I click a user's post, it redirects me to that post's show page.
- When I click to see all posts, it redirects me to the user's post's index page.

User post index page:
- I can see the user's profile picture.
- I can see the user's username.
- I can see the number of posts the user has written.
- I can see a post's title.
- I can see some of the post's body.
- I can see the first comments on a post.
- I can see how many comments a post has.
- I can see how many likes a post has.
- I can see a section for pagination if there are more posts than fit on the view.
- When I click on a post, it redirects me to that post's show page.

Post show page:
- I can see the post's title.
-  can see who wrote the post.
- I can see how many comments it has.
- I can see how many likes it has.
- I can see the post body.
- I can see the username of each commentor.
- I can see the comment each commentor left.

2022-09-27 23:18 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @fibini and @dqarias,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Gitflow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-27 23:18 UTC, omar-muhamad commented on README.md
>  Give a ⭐️ if you like this project!
- [ ] Please add the instructions about how to `install required gems`, `create and run migrations for the database`, and `how to run tests` under Getting started section in your readme file to make it more professional.

2022-09-27 23:18 UTC, omar-muhamad commented on spec/views/users/index.html.erb_spec.rb
> +      expect(page).to have_xpath("//img[contains(@src,'#{@third_user.photo}')]")
- [x] Please make these in a separate test case like the following:
```ruby
it 'show the user photo' do
    'Put the tests here'
end
```

2022-09-27 23:18 UTC, omar-muhamad commented on spec/views/users/show.html.erb_spec.rb
> +      expect(page).to have_xpath("//img[contains(@src,'#{@first_user.photo}')]")
- [x] Same here, Please put every one of these tests in a separate test case.

2022-09-27 23:18 UTC, Omar-Muhamad commented on spec/views/users/show.html.erb_spec.rb
> +      expect(page).to have_current_path(user_posts_path(@first_user))
- [ ]  Same here, Please put every one of these tests in a separate test case.

2022-09-27 23:18 UTC, Omar-Muhamad commented on spec/views/posts/index.html.erb_spec.rb
> +      expect(page).to have_xpath("//img[contains(@src,'#{@first_user.photo}')]")
- [ ] Same here, Please put every one of these tests in a separate test case.

2022-09-27 23:18 UTC, Omar-Muhamad commented on spec/views/posts/index.html.erb_spec.rb
> +      expect(page).to have_content('Likes: 1')
- [ ]  Same here, Please put every one of these tests in a separate test case.

2022-09-27 23:18 UTC, Omar-Muhamad commented on spec/views/posts/index.html.erb_spec.rb
> +      expect(page).to have_current_path(user_post_path(@first_user, @first_post))
- [ ]  Same here, Please put every one of these tests in a separate test case.

2022-09-27 23:18 UTC, Omar-Muhamad commented on spec/views/posts/show.html.erb_spec.rb
> +      expect(page).to have_content("Likes: #{@first_post.likes_counter}")
- [ ]  Same here, Please put every one of these tests in a separate test case.

2022-09-27 23:18 UTC, Omar-Muhamad commented on spec/views/posts/show.html.erb_spec.rb
> +      expect(page).to have_content(@second_comment.text)
- [ ]  Same here, Please put every one of these tests in a separate test case.

2022-09-28 00:24 UTC, cwaku approved these changes
Hi @fibini 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
 - [x] Correct GitHub Flow 👍🏾 
 - [x] Good commit history 🥇 
 - [x] Good PR title/description 💯 
 - [x] All linters passed 🥇 
 
![](https://media.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. The previous reviewer simply missed some of them, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 00:45 UTC, merged